version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-simedis
    network_mode: bridge
    ports:
      #APP-SIMEDIS
      - 20003:20003
    volumes:
      - ./:/data/app-simedis/:rw
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
