version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-simedis
    network_mode: bridge
    ports:
      - 8111:8111
    volumes:
      - ./:/var/www/html/:rw
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
